### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by explrA** [dmort27/epitran#152]
I am trying to use Epitran for English language and I am getting IndexError when trying to run the following code:
(It works fine for other langauges apart from English)
```
import epitran
import regex
epi = epitran.Epitran('eng-Latn')
print(epi.transliterate(u'Berkeley'))
```

Gives me the following error
```
WARNING:epitran:lex_lookup (from flite) is not installed.
Traceback (most recent call last):
  File "/epi_test.py", line 4, in <module>
    print(epi.transliterate(u'Berkeley'))
  File "/home/epienv/lib/python3.10/site-packages/epitran/_epitran.py", line 52, in transliterate
    return self.epi.transliterate(word, normpunc, ligatures)
  File "/home/epienv/lib/python3.10/site-packages/epitran/flite.py", line 96, in transliterate
    acc.append(self.english_g2p(chunk))
  File "/home/epienv/lib/python3.10/site-packages/epitran/flite.py", line 214, in english_g2p
    arpa_text = arpa_text.splitlines()[0]
IndexError: list index out of range
```

Versions being used:
Python - 3.10.1
Epitran - 1.24

Can someone please help me resolve this issue.

TIA,
explr

**Comment by caixxiong** [comment]
The same question to me

**Comment by dmort27** [comment]
Did you install the `lex_lookup` binary from `flite`, as described in the README?
