### ISSUE TITLE
help please: couldn't get the amh-Ethi working

### ISSUE THREAD

**Issue by surawinfo** [dmort27/epitran#2]
Here is the traceback for using the Epitran("amh-Ethi"), for other languages it works fine.

>>> import epitran
>>> epi = epitran.Epitran("amh-Ethi")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "epitran/_epitran.py", line 42, in __init__
    self.epi = SimpleEpitran(code, preproc, postproc, ligatures)
  File "epitran/simple.py", line 52, in __init__
    self.postprocessor = PrePostProcessor(code, 'post')
  File "epitran/ppprocessor.py", line 28, in __init__
    self.rules = self._read_rules(code, fix)
  File "epitran/ppprocessor.py", line 38, in _read_rules
    return Rules([abs_fn])
  File "epitran/rules.py", line 28, in __init__
    rules = self._read_rule_file(rule_file)
  File "epitran/rules.py", line 36, in _read_rule_file
    rules.append(self._read_rule(line))
  File "epitran/rules.py", line 65, in _read_rule
    return self._fields_to_function(a, b, X, Y)
  File "epitran/rules.py", line 81, in _fields_to_function
    regexp = re.compile(left)
  File "/home/anaconda2/lib/python2.7/site-packages/regex.py", line 345, in compile
    return _compile(pattern, flags, kwargs)
  File "/home/anaconda2/lib/python2.7/site-packages/regex.py", line 490, in _compile
    caught_exception.pos)
_regex_core.error: missing ) at position 53

**Comment by dmort27** [comment]
This is a problem in the post-processor for Amharic. I'll look into it now.

**Comment by dmort27** [comment]
Fixed on GitHub. Warning: IPA output from Amharic contains superfluous vowels.

**Comment by surawinfo** [comment]
Thank you! for the help David :+1:
