### ISSUE TITLE
lex_lookup (from flite) is not installed

### ISSUE THREAD

**Issue by PasaOpasen** [dmort27/epitran#52]
How to solve this problem?
```python
import epitran

epi = epitran.Epitran('eng-Latn')

epi.transliterate('Hello')
```

```
WARNING:root:lex_lookup (from flite) is not installed.
Traceback (most recent call last):

  File "<ipython-input-3-9e6f98d7c4c9>", line 1, in <module>
    epi.transliterate('Hello')

  File "C:\ProgramData\Anaconda3\lib\site-packages\epitran\_epitran.py", line 62, in transliterate
    return self.epi.transliterate(word, normpunc, ligatures)

  File "C:\ProgramData\Anaconda3\lib\site-packages\epitran\flite.py", line 94, in transliterate
    acc.append(self.english_g2p(chunk))

  File "C:\ProgramData\Anaconda3\lib\site-packages\epitran\flite.py", line 212, in english_g2p
    arpa_text = arpa_text.splitlines()[0]

IndexError: list index out of range
```

It's working for other languages but not english

**Comment by dmort27** [comment]
English support requires the installation of `lex_lookup` from the Flite speech synthesis package. See the README (specifically [https://github.com/dmort27/epitran#installation-of-flite-for-english-g2p](https://github.com/dmort27/epitran#installation-of-flite-for-english-g2p)). There has been some difficulty getting this to compile properly on Windows.
