### ISSUE TITLE
Chinese traditional doesn't seem to work

### ISSUE THREAD

**Issue by ftyers** [dmort27/epitran#71]
```python
>>> import epitran
>>> epi = epitran.Epitran('cmn-Hans', cedict_file='zh')
>>> epi.transliterate('为什么')
'weiʂenme'
>>> epi = epitran.Epitran('cmn-Hant', cedict_file='zh')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fran/.local/lib/python3.8/site-packages/epitran/_epitran.py", line 44, in __init__
    self.epi = self.special[code](ligatures=ligatures, cedict_file=cedict_file, tones=tones)
TypeError: __init__() got an unexpected keyword argument 'tones'
```

**Comment by ftyers** [comment]
Probably the constructor should allow the tones argument:
```python
class EpihanTraditional(Epihan):
    def __init__(self, ligatures=False, cedict_file=None, rules_file='pinyin-to-ipa.txt'):
```

**Comment by ftyers** [comment]
This is a duplicate of #68.
