### ISSUE TITLE
importerror in python3.6

### ISSUE THREAD

**Issue by jonorthwash** [dmort27/epitran#73]
```
$ python3.6
Python 3.6.8rc1 (default, Dec 12 2018, 06:12:40) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import epitran
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/pypy3.6/dist-packages/epitran/__init__.py", line 1, in <module>
    from epitran._epitran import Epitran
  File "/usr/local/lib/pypy3.6/dist-packages/epitran/_epitran.py", line 8, in <module>
    import panphon.featuretable
  File "/usr/local/lib/pypy3.6/dist-packages/panphon/__init__.py", line 2, in <module>
    from panphon.featuretable import FeatureTable
  File "/usr/local/lib/pypy3.6/dist-packages/panphon/featuretable.py", line 9, in <module>
    import numpy
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.6 from "/usr/bin/python3.6"
  * The NumPy version is: "1.19.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

```

**Comment by dmort27** [comment]
[Other people](https://github.com/numpy/numpy/issues/11871) have reported a similar error with `numpy` when using `tensorflow` and other packages. Have you tried:

```
pip install --upgrade numpy
```
